name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_NEWKEY }}

      - name: do all
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.210.154.160 << 'EOF'
            REPO_URL="https://github.com/catstring/laravel-twitter.git"
            PROJECT_DIR="/var/www"
            PROJECT-NAME="laravel-twitter"

            sudo chown -R ec2-user:ec2-user \$PROJECT_DIR

            cd \$PROJECT_DIR           
            if [ ! -d "\$PROJECT-NAME" ]; then
              sudo git clone \$REPO_URL
              composer install
            else
              cd \$PROJECT-NAME
              sudo git pull
            fi

            sudo chown -R nginx:nginx \$PROJECT_DIR
          EOF

